### ISSUE TITLE
Error: Don't know how to handle 'options.size' type: undefined

### ISSUE THREAD

**Issue by KaMaToZzz** [VROOM-Project/vroom-docker#63]
Hello, I have a problem with deploy version highest then VROOM_RELEASE=v1.9.0 and VROOM_EXPRESS_RELEASE=v0.7.0:

`
Error: Don't know how to handle 'options.size' type: undefined
    at Object.size (/vroom-express/node_modules/rotating-file-stream/index.js:557:19)
    at checkOpts (/vroom-express/node_modules/rotating-file-stream/index.js:660:20)
    at Object.createStream (/vroom-express/node_modules/rotating-file-stream/index.js:702:18)
    at Object.<anonymous> (/vroom-express/src/index.js:32:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vroom-express@0.8.0 start: `node src/index.js`
npm ERR! Exit status 1

 
npm ERR! Failed at the vroom-express@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-08T11_05_47_045Z-debug.log
`

Dockerfile:
`
FROM debian:buster-slim as builder
LABEL maintainer=nils@gis-ops.com

WORKDIR /

RUN echo "Updating apt-get and installing dependencies..." && \
  apt-get -y update > /dev/null && apt-get -y install > /dev/null \
  git-core \
  build-essential \
	g++ \
  libssl-dev \
	libasio-dev \
	pkg-config

ARG VROOM_RELEASE=v1.10.0

RUN echo "Cloning and installing vroom release ${VROOM_RELEASE}..." && \
    git clone https://github.com/VROOM-Project/vroom.git && \
    cd vroom && \
    git fetch --tags && \
    git checkout -q $VROOM_RELEASE && \
    make -C /vroom/src && \
    cd /

# TODO: change to release version again
ARG VROOM_EXPRESS_RELEASE=v0.8.0

RUN echo "Cloning and installing vroom-express release ${VROOM_EXPRESS_RELEASE}..." && \
    git clone https://github.com/VROOM-Project/vroom-express.git && \
    cd vroom-express && \
    git fetch --tags && \
    git checkout $VROOM_EXPRESS_RELEASE

FROM node:12-buster-slim as runstage
COPY --from=builder /vroom-express/. /vroom-express
COPY --from=builder /vroom/bin/vroom /usr/local/bin

WORKDIR /vroom-express

RUN apt-get update > /dev/null && \
    apt-get install -y --no-install-recommends \
      libssl1.1 \
      curl \
      > /dev/null && \
    rm -rf /var/lib/apt/lists/* && \
    # Install vroom-express
    npm config set loglevel error && \
    npm install && \
    # To share the config.yml & access.log file with the host
    mkdir /conf

COPY ./config.yml /vroom-express/config.yml
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
ENV VROOM_DOCKER=osrm \
    VROOM_LOG=/conf

HEALTHCHECK --start-period=10s CMD curl --fail -s http://localhost:3000/health || exit 1

EXPOSE 3000
ENTRYPOINT ["/bin/bash"]
CMD ["/docker-entrypoint.sh"]

`
Work fine on: VROOM_RELEASE=v1.9.0 and VROOM_EXPRESS_RELEASE=v0.7.0
Got errors on: VROOM_RELEASE=v1.10.0 and VROOM_EXPRESS_RELEASE=v0.8.0

**Comment by nilsnolde** [comment]
Sorry I won’t support older versions. But I’m happy to look at a PR if you manage to fix the issue.
